# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mov-12',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/mov-12',
                'lib_path': 'mov_12'},
  'syms': {'mov_12.core': {'mov_12.core.foo': ('core.html#foo', 'mov_12/core.py')}}}