# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/movie_recommender.ipynb.

# %% auto 0
__all__ = ['get_movie_recs']

# %% ../nbs/movie_recommender.ipynb 12
def get_movie_recs(full_title):
    "This function will use the `nn.CosineSimilarity` on the 50 latent factors for each movie to find the 30 movies most similar to your favorite movie."
    movie_factors = learn.model.i_weight.weight
    idx = dls.classes['title'].o2i[full_title]
    distances =  nn.CosineSimilarity(dim=1)(movie_factors,movie_factors[idx][None])
    idx = distances.argsort(descending=True)
    return [o for o in dls.classes['title'][idx][:30]]
